// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Anime
export const REQUEST_ANIME_LIST = "REQUEST_ANIME_LIST";
export const SUCCESS_ANIME_LIST = "SUCCESS_ANIME_LIST";
export const ERROR_ANIME_LIST = "ERROR_ANIME_LIST";

export const REQUEST_DELETE_ANIME = "REQUEST_DELETE_ANIME";
export const SUCCESS_DELETE_ANIME = "SUCCESS_DELETE_ANIME";
export const ERROR_DELETE_ANIME = "ERROR_DELETE_ANIME";
export const CLEAR_DELETE_ERROR = "CLEAR_DELETE_ERROR";

export const REQUEST_ANIME_DETAILS = "REQUEST_ANIME_DETAILS";
export const SUCCESS_ANIME_DETAILS = "SUCCESS_ANIME_DETAILS";
export const ERROR_ANIME_DETAILS = "ERROR_ANIME_DETAILS";

export const REQUEST_SAVE_ANIME = "REQUEST_SAVE_ANIME";
export const SUCCESS_SAVE_ANIME = "SUCCESS_SAVE_ANIME";
export const ERROR_SAVE_ANIME = "ERROR_SAVE_ANIME";
export const CLEAR_SAVE_ERROR = "CLEAR_SAVE_ERROR";